train_file_path: <insert_file_path>  # file_path of .csv file
test_data_config:  <insert_option>  # empty, integer, or file_path of .csv file
draw_plots: True  # decides if images are drawn
draw_reconstructions: auto  # decides if reconstruction plots are drawn. auto draws if channels <= 20
num_to_show: 1536  # datapoints from index 0 (inclusive) that are plotted
verbose_model: False
