data:
  train_file_path: <insert_file_path>  # file_path of .csv file
  test_data_config: <insert_option> # empty, integer, or file_path of .csv file

other:
  draw_plots: True  # decides if images are drawn
  draw_reconstructions: auto  # decides if reconstruction plots are drawn. "auto" draws if channels <= 20
  error_plot: between # picks how error between real and reconstructed error is drawn. "between" or "floor"
  verbose_model: False

model:
  input_neurons: 16
  epochs: 200
  strides: 1
  pool_size: 4
  kernel_size: 7
  activation: relu
  optimizer: adam
  loss: mean_absolute_error  # mean_absolute_error, mean_squared_error, mean_squared_logarithmic_error, huber, log_cosh
  threshold_quantile: 0.99  # 0 to 1
